# Generated by Django 3.2.8 on 2021-11-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_product_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imgage',
            new_name='image',
        ),
    ]
