# Generated by Django 3.2.8 on 2021-11-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='year',
            new_name='price',
        ),
    ]
