# Generated by Django 3.2.8 on 2021-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20211102_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.CharField(default='admin', max_length=64),
            preserve_default=False,
        ),
    ]
