# Generated by Django 3.2.8 on 2021-11-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
