# Generated by Django 3.2.8 on 2021-11-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_product_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='auctions.Product'),
        ),
    ]
