# Generated by Django 3.2.8 on 2021-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20211103_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Product'),
        ),
    ]
