# Generated by Django 3.2.8 on 2021-11-03 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_user_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
