# Generated by Django 3.2.8 on 2021-11-03 13:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20211103_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watch_list',
        ),
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
