# Generated by Django 3.2.8 on 2021-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20211103_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('creator', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
    ]
