# Generated by Django 3.2.8 on 2021-11-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
