# Generated by Django 3.2.8 on 2021-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.IntegerField()),
            ],
        ),
    ]
