# Generated by Django 3.2.8 on 2021-11-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_bidform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BidForm',
        ),
    ]
